name: Check Library Version, Merge PR, and Create Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Arduino Library Deploy
        # You may pin to the exact commit or the version.
        # uses: ktauchathuranga/arduino-library-deploy@51a9f8fb0e06cd8d19738aebc949bcc3734ceeb8
        uses: ktauchathuranga/arduino-library-deploy@v1.0.2
        with:
          # GitHub token for API requests.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
