name: Check Library Version, Validate, Merge PR, and Create Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for reading code
      pull-requests: write  # Required for merging PRs
      issues: write  # Optional, for managing PR issues
      repository-projects: write  # Optional
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Arduino Library Deploy
        uses: ktauchathuranga/arduino-library-deploy@v2.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use Personal Access Token if needed
