name: Check Library Version and Create Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout PR Code
      uses: actions/checkout@v3

    # Extract the version from the PR
    - name: Get Version from Pull Request
      id: pr_version
      run: |
        pr_version=$(grep '^version=' library.properties | cut -d'=' -f2)
        echo "::set-output name=pr_version::$pr_version"

    # Fetch the main branch library.properties
    - name: Fetch Main Branch Version
      run: |
        git fetch origin main
        git checkout origin/main -- library.properties
        main_version=$(grep '^version=' library.properties | cut -d'=' -f2)
        echo "::set-output name=main_version::$main_version"

    # Compare the versions
    - name: Compare Versions
      id: compare_versions
      run: |
        if [ "${{ steps.pr_version.outputs.pr_version }}" = "${{ steps.main_version.outputs.main_version }}" ]; then
          echo "PR version is the same as the main branch version."
          echo "::set-output name=status::fail"
          exit 1
        else
          echo "PR version is different from the main branch version."
          echo "::set-output name=status::pass"
        fi

    # Create a release if the versions differ
    - name: Create GitHub Release
      if: steps.compare_versions.outputs.status == 'pass'
      uses: actions/create-release@v1
      with:
        tag_name: v${{ steps.pr_version.outputs.pr_version }}
        release_name: Release v${{ steps.pr_version.outputs.pr_version }}
        body: |
          **Changelog**
          - Updated to version ${{ steps.pr_version.outputs.pr_version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
